from error.BaseException import BaseException


class ValidationException(BaseException):
    pass
